FROM ubuntu:20.04
LABEL maintainer="Dika Priska"
LABEL version="0.1"

COPY syncher.sh .

RUN apt update 
RUN apt install ldap-utils mysql-client -y 
RUN rm -rf /var/lib/apt

RUN chmod a+x syncher.sh

ENV MYSQL_USER="test"
ENV MYSQL_PASS="test"
ENV MYSQL_HOST="test"
ENV MYSQL_PORT="test"
ENV LDAP_USER="test"
ENV LDAP_HOST="test"
ENV LDAP_PASS="test"
ENV LDAP_PORT="test"
ENV LDAP_BASE="test"

ENTRYPOINT ["bash","syncher.sh"]
